joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 2
      y: 3
    scale_linear:
      x: 0.2
      y: 0.2
    scale_linear_turbo:
      x: 0.5
      y: 0.5

    axis_angular:
      yaw: -1

    #publish_stamped_twist: true
    enable_button: 7
    enable_turbo_button: 8

    require_enable_button: false