controller_manager:
  ros__parameters:
    update_rate: 30

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_controller:
  ros__parameters:
    reference_timeout: 5.0

    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true

    kinematics:
      wheel_base: 0.385
      wheel_separation: 0.575
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.055
      sum_of_robot_center_projection_on_X_Y_axis: 1.0
      #base_frame_offset: { x: 1.0, y: 2.0, theta: 3.0 }
      #wheels_radius: 0.055
      #sum_of_robot_center_projection_on_X_Y_axis: 0.2925
      
      

    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    #twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    #pose_covariance_diagonal: [0.0, 6.0, 12.0, 18.0, 24.0, 30.0]
    #pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    #twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    use_stamped_vel: false
    in_chained_mode: false